In [54]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D, InputLayer
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Sequential
#import smote
from imblearn.over_sampling import RandomOverSampler
import numpy as np

In [55]:
def generate_and_gate_data(num_samples):
    # Generate random binary inputs (x1, x2)
    x = np.random.randint(0, 2, size=(num_samples, 2))
    # Compute the AND output
    y = np.logical_and(x[:, 0], x[:, 1]).astype(int)
    return x, y

x, y = generate_and_gate_data(1000)

model = Sequential([
    InputLayer(shape=(2,)),
    Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer=Adam(), metrics=['accuracy'])
model.fit(x, y, epochs=100, batch_size=32, validation_data=(
    x, y))


Epoch 1/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5050 - loss: 0.6921 - val_accuracy: 0.5000 - val_loss: 0.6875
Epoch 2/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step - accuracy: 0.5395 - loss: 0.6845 - val_accuracy: 0.7590 - val_loss: 0.6791
Epoch 3/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 702us/step - accuracy: 0.7673 - loss: 0.6762 - val_accuracy: 0.7590 - val_loss: 0.6708
Epoch 4/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 763us/step - accuracy: 0.7583 - loss: 0.6684 - val_accuracy: 0.7590 - val_loss: 0.6633
Epoch 5/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - accuracy: 0.7727 - loss: 0.6602 - val_accuracy: 0.7590 - val_loss: 0.6561
Epoch 6/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - accuracy: 0.7624 - loss: 0.6538 - val_accuracy: 0.7590 - val_loss: 0.6493
Epoch 7/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - accuracy: 0.8086 - loss: 0.6478 - val_accuracy: 1.0000 - val_loss: 0.6429
Epoch 8/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step - accuracy: 0.9885 - loss: 0.6400 - val_accura

In [56]:
x

array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [1, 0],
       [1, 1],
       [1, 0]])

In [57]:
model.predict(x)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step


array([[0.09424613],
       [0.27671847],
       [0.09424613],
       [0.27671847],
       [0.29784188],
       [0.29784188],
       [0.27671847],
       [0.09424613],
       [0.60932225],
       [0.09424613],
       [0.60932225],
       [0.09424613],
       [0.27671847],
       [0.27671847],
       [0.29784188],
       [0.29784188],
       [0.27671847],
       [0.29784188],
       [0.09424613],
       [0.29784188],
       [0.60932225],
       [0.60932225],
       [0.60932225],
       [0.09424613],
       [0.27671847],
       [0.27671847],
       [0.60932225],
       [0.60932225],
       [0.09424613],
       [0.27671847],
       [0.09424613],
       [0.09424613],
       [0.60932225],
       [0.27671847],
       [0.09424613],
       [0.27671847],
       [0.60932225],
       [0.27671847],
       [0.27671847],
       [0.27671847],
       [0.27671847],
       [0.29784188],
       [0.09424613],
       [0.29784188],
       [0.27671847],
       [0.60932225],
       [0.29784188],
       [0.297

In [33]:
x

array([[1, 0],
       [0, 1],
       [0, 0],
       [1, 1]])

In [48]:
len(x_train)

8